class File {

	/**
	 * 
	 * @param {string} code generated by application to search a file
	 * @param {string} filename 
	 * @param {string} isProcessed
	 * @param {string} details 
	 */
	constructor(code, filename, isProcessed, data, details) {
		this.code = code;
		this.data = data;
		this.details = details;
		this.filename = filename;
		this.isProcessed = isProcessed;
	}
}

module.exports = File;
