version: "3.2"
services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.11-management-alpine
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
        - 5673:5672
        - 15673:15672
    networks:
        - rabbitmq_nodejs
  
  api_and_consumer:
    container_name: api_and_consumer
    build:
      context: ./
      target: dev
    volumes:
      - ./src:/src
      - /src/node_modules
    ports:
      - 3000:3000
    depends_on:
      - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node infra/index.js'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_nodejs

networks:
  rabbitmq_nodejs:
    driver: bridge